name: Lobsters Data Import
on:
  push:
    paths:
      - .github/workflows/lobsters.yml
  workflow_dispatch:
  schedule:
    - cron: '*/60 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3.5.1
      - name: Fetch newest
        uses: githubocto/flat@v3.4.0
        with:
          authorization: AMYS_SECRET
          http_url: https://${{ secrets.AMYS_SECRET }}@lobste.rs/newest.json
          downloaded_filename: newest.json
          
         
